path:
  data: "../data"

  data_property: "./properties/movie_len.yaml"

  model_property: "./model/GRU4Rec.yaml"

  train_valid_property: "./train_eval.yaml" 

  save_data: "./dataset/recbole_data"

  save_yaml: "./test/test.yaml"

  save_model: "./saved/GRU4Rec-Jun-21-2023_02-27-19.pth"

  submission: "./submission"

model: "GRU4Rec"

