path:
  data: "../data"

  data_property: "./properties/movie_len.yaml"

  model_property: "./model/CORE.yaml"

  train_valid_property: "./train_eval.yaml" 

  save_data: "./dataset/datav4"

  save_yaml: "./test/test.yaml"

  save_model: "./saved/CORE-Jun-22-2023_06-12-21.pth"

  submission: "./submission"

