path:
  data: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/datav4"

  data_property: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/properties/movie_len.yaml"

  model_property: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/model/DeepFM.yaml"

  train_valid_property: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/context_aware_config.yaml" 

  save_data: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/recbole_data"

  save_yaml: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/test/test.yaml"

  save_model: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/saved/DeepFM-Jun-21-2023_15-42-29.pth"

  submission: "/opt/ml/movie_rec_project/level2_movierecommendation-recsys-06/recbole_ex/submission"
model: "DeepFM"

