# Training and evaluation config
epochs: 50
train_batch_size: 2048
eval_batch_size: 2048
train_neg_sample_args:
    distribution: 'uniform'
eval_args:
    group_by: user
    order: TO
    split: {'LS': 'valid_and_test'}
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: Recall@10